### ISSUE TITLE
AdGuard for Android doesn't work on HTTPS sites

### ISSUE THREAD

**Issue by fivefilters** [fivefilters/block-ads#1]
So the test on [https://blockads.fivefilters.org](https://blockads.fivefilters.org) shows that there's no blocker running. Running without HTTPS on [http://blockads.nfshost.com](http://blockads.nfshost.com) works.

But AdGuard also has an acceptable ads program. Haven't figured out how to test for that yet. (The one currently in use doesn't work for it.)

Adguard acceptable ads list: https://adguard.com/en/filter-rules.html?id=10

**Comment by ameshkov** [comment]
Current stable version of AG for Android cannot filter HTTPS.

You can check out the alpha version though:
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.5.8-alpha

**Comment by ameshkov** [comment]
The test is broken by AG for Android as test images are removed from the page code.

So these are undefined in this case:

```
$("img#test-ad")[0]
$("img#test-whitelist")[0]
```

**Comment by fivefilters** [comment]
Hi Andrey, thanks for that. You mean because they have 'test' in the id attribute?

The previous version, when we weren't relying solely on images, was showing some blocking by AG for Android on the non-HTTPS version of the test. So I was surprised when the updated version was showing zero blocking. But didn't get a chance to investigate. We'll update soon - either checking for presence of elements or changing the attribute values.

We'll respond to your other issue later today.

**Comment by ameshkov** [comment]
> You mean because they have 'test' in the id attribute?

No. Let me elaborate on how it works so you can understand it better.

There're three filtering methods in AG for Android: simplified, high-speed, high-quality.
- Simplified: simply blocks web requests
- High speed: blocks web requests and injects cosmetic CSS/JS into the page code.
- High quality: all above plus parse the page HTML code and remove blocked elements from the code. In your case both images should be blocked by URL, so AG will remove `<img>` tags.

Without full-scaled HTTPs filtering AG cannot get to that page code, so the only thing it does is blocking on the domain-level.

> So I was surprised when the updated version was showing zero blocking

I guess you were using another domain back then. You now use `fusionads.net` to test. AG blocks all third-party requests to that domain with a rule like that: `||fusionads.net^$third-party`.

But when HTTPs filtering is disabled (or not present as in current stable version) AG does not know if request is third-party or not, so it does not block it. For ad networks domains we add special rules with $empty modifier to mobile ads filter so that Android version could block it even without https filtering. Missed fusionads.net though, I'll add it to mobile ads filter now.

**Comment by fivefilters** [comment]
Thanks Andrey,

We have a non-HTTPS page at: http://blockads.nfshost.com - so I assume the issues around Adguard and HTTPS will not apply to that page. But it still seems not to be blocking. In our previous version of the adblock test (where we loaded ads.css from our own domain), Adguard was blocking the css from loading. But with this new test (where we load images), it doesn't seem to be blocking.

I thought maybe it was because test images were being removed by Adguard some other way and we weren't detecting it, but you seem to be saying it's not that.

**Comment by ameshkov** [comment]
Hm, something is wrong with the way you check as both requests are blocked with high-speed filtering method.
<img width="1327" alt="00001016" src="https://cloud.githubusercontent.com/assets/5947035/13635502/26eb72b4-e60d-11e5-83a4-8f7ee4102ee0.png">

With high-quality filtering method page is broken:
<img width="1327" alt="2016-03-09_1540" src="https://cloud.githubusercontent.com/assets/5947035/13635530/69b1193c-e60d-11e5-8fcd-7c5718585346.png">

**Comment by ameshkov** [comment]
Ah, one more thing.

You use https url here:
`<img id="test-whitelist" src="https://gstatic.com/ui/v1/icons/mail/images/cleardot.gif?ads=1" style="visibility: hidden;" />`

So it won't be blocked in high-speed mode with https filtering disabled.

**Comment by fivefilters** [comment]
Thanks, we're going to look into it and see what we can do. Appreciate the help in troubleshooting this. Will update soon.

**Comment by fivefilters** [comment]
Andrey, investigated some more and here's what we've found. Adguard on Android seems to respond to requests with a 500 status code but with valid headers, e.g. 

```
Content-Length:322
Content-Type:image/png
```

Google Chrome's inspector sees this as a 1x1 PNG. The code we were using to check if the image had loaded was seeing that response and treating it as a successful image load. Even the very popular and cross platform [imagesLoaded](https://github.com/desandro/imagesloaded) tool treats it as a successful load:

```
GET http://fusionads.net/images/logo.png 500 (Request Blocked)
(index):161 image is loaded for http://fusionads.net/images/logo.png
(index):161 image is loaded for https://gstatic.com/ui/v1/icons/mail/images/cleardot.gif?ads=1
(index):151 all images loaded
(index):154 all images successfully loaded
```

We'll see if we can figure something out here. Will investigate more later.

**Comment by ameshkov** [comment]
Yeah, we return 1x1 transparent png for blocked images just in case.

If you use some bigger image from gstatic instead of cleardot.gif (which is 1x1), you could check the image size.

Something like that:

```
                if (typeof img.naturalWidth !== "undefined" && img.naturalWidth <= 1) {
                        return false;
                }
```

Image example:
https://www.gstatic.com/webp/gallery3/1.png
http://www.gstatic.com/webp/gallery3/1.png

**Comment by fivefilters** [comment]
Thanks Andrey, this should be fixed now.

**Comment by ameshkov** [comment]
Hi!

The case when image is removed by AG is not yet handled.

Suggested fix:

```
        // function to check if image has loaded, taken from http://stackoverflow.com/a/1977898
        function isImageOk(img) {
                // Image was removed from the page code (issue #1)
                if (typeof img == 'undefined') {
                    return false;
                }
                // During the onload event, IE correctly identifies any images that
                // weren’t downloaded as not complete. Others should too. Gecko-based
                // browsers act like NS4 in that they report this incorrectly.
                if (!img.complete) {
                        return false;
                }

                // However, they do have two very useful properties: naturalWidth and
                // naturalHeight. These give the true size of the image. If it failed
                // to load, either of these should be zero.
                if (typeof img.naturalWidth !== "undefined" && img.naturalWidth <= 1) {
                        return false;
                }

                // No other way of checking: assume it’s ok.
                return true;
        }

```

**Comment by fivefilters** [comment]
Thanks Andrey, updated the code to handle this case.
