### ISSUE TITLE
Why Adguard is in the same list with Adblock and Adblock Plus?

### ISSUE THREAD

**Issue by ameshkov** [fivefilters/block-ads#3]
It is pretty clear that unlike these two we don't receive money from publishers.

https://adguard.com/en/whitelist.html

> Introduction. This list has nothing to do with «Acceptable Ads» program from Adblock Plus. We do not get paid by site owners. Ads listed here are not «acceptable», but useful to many users. At the moment, the list contains mostly search contextual ads (which are often more helpful than the search results) and self promo ads (promotion of the website’s own content). If you do not want to see these ads, just do not turn on «Filter for useful ads».

It is just misleading that AG is listed there as we have nothing to do with that section description. Taboola case is really shocking, and from the article it seems that we are related to this.

> The list of 'acceptable' advertisers is always growing.

You've seen the list. It is very short and it is not growing. There are only self promo ads and seach contextual ads. Both types are obviously useful to users which is why that filter exists.
Self promo example: deals promotions on amazon.com. In general we are trying to not block such things (due to our policy: https://blog.adguard.com/en/adguard-news/adguard-filter-policy.html). But if it is blocked by some "wide" filter rule, we unblock it in useful ads filter.

**Comment by fivefilters** [comment]
Andrey, thanks for the help in the other thread. I hope this explains why you're listed here. 

> It is pretty clear that unlike these two we don't receive money from publishers.

The issue is not whether you receive money or not. Adblock Plus receives money, but it also accepts ads for free if they meet their guidelines. The issue is the whole idea of having acceptable ads. You might think calling them 'useful ads' sets you apart, but in our eyes, it's the same thing. Even if at the moment you do not include the more egregious stuff Adblock and Adblock Plus do, like Taboola.

> There are only self promo ads and seach contextual ads. Both types are obviously useful to users which is why that filter exists.

Neither is "obviously" useful to users. I think it's rather presumptuous of you to think they are, especially considering that you're selling Adguard as offering users a "pure" Internet experience. Our project is trying to encourage users to reject all ads, and judging from the response we've received, many agree with that sentiment. So obviously we take a different view to you on this, and that's why we urge users to stay away from projects which have embraced 'acceptable' ads.

I should also mention that you are currently misleading your users about your [useful ads](https://adguard.com/en/whitelist.html) programme. You write (and you quoted this in your response above):

> If you do not want to see these ads, just do not turn on «Filter for useful ads».

Further down on the same page:

> **But I don’t want to see any ads!**
> No problem, simply do not enable this function when installing the program.

'Useful ads' are enabled by default in both your Chrome extension and your Android application. It's not a matter of 'not enabling' or 'not turning on'. You've decided these ads are so useful that all your users should see them. You should be telling them to turn it off or disable it if they don't like it.

**Comment by ameshkov** [comment]
> The issue is the whole idea of having acceptable ads. You might think calling them 'useful ads' sets you apart, but in our eyes, it's the same thing.

The whole acceptable ads thing is a way for ABP to monetize their ad blocker, so in my eyes it is very different from our case. 

But I got your point from the article, it's pretty obvious that we won't agree on this:)
Let me close that issue then.

> I think it's rather presumptuous of you to think they are

The list is based on users complaints (not site owners, which is also an important difference). 

Honestly, I don't think that this is a good way to have a filter managed by somebody deciding what's good for you. This experiment just shows that most users do not care.

However, I don't agree with you on the "reject all ads" statement. In the end, user is the one who should make the decision what to block or not. But to make the decision user should understand the consequences.

Broadly speaking:
- Block all ads → have an internet behind paywall + hidden sponsored content everywhere.
- Unblock all ads → forget about your privacy and have really annoying ads everywhere.

I don't like both and I suppose there should be a right balance somewhere. However, I don't know what that balance is and how to reach it.

> I should also mention that you are currently misleading your users about your useful ads programme. You write (and you quoted this in your response above):

Yep, the program default settings depends on the OS, we should make it clear in that sentence. For instance on iOS that filter is disabled by default. I guess the same will be done on Android in future versions (currently due to lack of https filtering having that filter on or off does not matter anyway).
